target/row-types

Data/Row/Variants.hs
With it now, we can write `unsafeCoerce`:
```
update :: KnownSymbol l => Label l -> a -> Var r -> Var r
unsafeCoerce :: a -> b
unsafeCoerce x = fromJust . view l . update l x $ singleton l undefined where l = Label @""
```
=> unbreak `Data.Row.Variants.update`

Data/Row/Internal.hs, Data/Row/Records.hs
This PR includes versions of `compose`, `uncompose`, `sequence`, and `labels` that don't require `Unconstrained1`. This avoids you from having to include multiple `Forall` constraints when one of them is `Unconstrained1`.
For consistency, I personally think that the `'`s should be on the more specific ones, but this breaks compatibility.
=> Don't require `Unconstrined1`

Data/Row/Internal.hs
Oops.  It should have been in there when I added the type family.
=> Add fixity declaration for .\/

Data/Row/Internal.hs, Data/Row/Records.hs, Data/Row/Variants.hs
https://github.com/target/row-types/issues/19
The primary motivation is to be able to use `.==` and `.+` to construct rows of kinds other than `*`. `Examples.lhs` compiles without any changes, however this change is potentially breaking because `Forall` is now poly-kinded and thus previously working programs may require additional annotations to compile.
The changes to the `Forall` class seem to be the sole reason why `Data.Row.Record` and `Data.Row.Variants` needed to be touched. At a high level it makes sense to me to make said class poly-kinded since we could have something like `newtype RecF (r :: Row (* -> *)) (a :: *)`, `newtype VarF (r :: Row (* -> *)) (a :: *)` for which we would be able to write instances `Forall f Functor => Functor (RecF r)`, `Forall f Functor => Functor (VarF …
=> Make type families in Data.Row.Internal polykinded

Data/Row/Records.hs
Inspired by SuperRecord (and with code just about lifted from it), I've added the ability to convert back and forth between Generic Haskell data types.
=> Add support for converting records to/from native Haskell types

Data/Row/Records.hs
mconcat was using some funny Semigroup instance, causing strange effects in
situations where shows was called with non-empty second argument.
So specify that we want to use Endo explicitly.
Fixes #25.
=> Fix Show instance for Rec

.gitignore, Data/Row/Records.hs
This PR adds the functions `toDynamicMap` and `fromDynamicMap` in `Data.Row.Record`.  These functions allow one to convert a `Rec` to and from the less typed `HashMap Text Dynamic`.
=> Add Dynamic HashMap compatibility

benchmarks/perf/Main.hs
I updated the benchmark suite.
This suite now also gives an indication of compile-time issues.  Currently, if you leave in the `SixtyFourRecord` code, this module takes many minutes to compile.  There is a moderate speedup if one removes the `FoldStep` code in `Data.Row.Internal`, but it's still pretty long.
Actual runtime performance seems pretty good.
I'd love to add some sort of benchmark that measures the memory footprint of these records, but that's for the future.
=> More thorough benchmarks

Data/Row/Internal.hs, Data/Row/Records.hs
I'm not sure what kind of problems removing `FoldStep` might have, but I don't think it's very useful.  For performance reasons, anyone writing their own `metamorph` functions will want to use the unsafe inject functions, and so `FoldStep` is not necessary.  Additionally, `FoldStep` is not always strong enough, meaning that the unsafe functions are the only possibility even if the `FoldStep` constraint is there.  In an ideal world, there would be a quick and easy constraint that is both simpler and more powerful than `FoldStep`, but I don't know what that is.
`Forall2` was a bit of a hack that I put together to support zipping two records together.  After seeing Issue https://github.com/target/row-types/issues/31, I was inspired to rewrite `Forall2` to make it more broadly useful: this …
=> Remove FoldStep and change Forall2 to Biforall

Data/Row/Records.hs, Data/Row/Variants.hs
I put these together for some new row-types examples I wrote up.  I think the instances work pretty well, but I'm open to suggestions if there's a better way to set the up.
=> Add Generic instances for Rec and Var

Data/Row/Records.hs, Data/Row/Variants.hs, examples/Examples.lhs, row-types.cabal
This PR adds instances for the generic-lens classes `HasField` and `AsContructor` for records and  variants respectively.  Now, if one imports `Data.Generic.Labels` from generic-lens, then viewing and updating records and variants can be done in a lensy way.
I've updated the examples file to reflect these changes.
Note also that this required a minor generalization of the Variant `focus` function to work -- it should be entirely backwards compatible (up to type inference, which I think should be fine too).
=> Add generic-lens compatibility

Data/Row/Records.hs, Data/Row/Variants.hs, examples/RowCSV.md
I saw a [post about CSV parsing using fancy types](http://oleg.fi/gists/posts/2019-07-15-fancy-types-for-cassava.html).  The author [claimed row-types wouldn't help](http://oleg.fi/gists/posts/2019-07-15-fancy-types-for-cassava.html#s:15), but I figured I could do it pretty trivially using _this_ row-types library.  So, I wrote it up.
=> Add native class exports to Records

Data/Row.hs, Data/Row/Dictionaries.hs, Data/Row/Internal.hs, Data/Row/Records.hs, Data/Row/Switch.hs, Data/Row/Variants.hs, examples/Examples.lhs, examples/RowCSV.hs, examples/RowCSV.md, examples/TypeSurgery.lhs, examples/TypeSurgery.md, examples/TypedErrors.lhs, examples/TypedErrors.md, row-types.cabal
This is a pretty large update to the internals of row-types, specifically with respect to `metamorph`.  Regular users probably won't be affected, but those calling `metamorph` themselves will certainly see breakages.
I rewrote `Forall`, folding the behavior of `metamorph'` into a more abstract version of `metamorph`.  I also adjusted the types so that you no longer need to use `unsafe` functions when calling `metamorph`.  Instead, there is now a module `Data.Row.Dictionaries` that exports a number of `Dict`s and entailments designed to help the type checker, and between the updated types and the dicts, you can get away with calling `metamorph` with normal variant and record operators.
While doing this, I realized that the function `unsafeRemove` for records didn't actually need to be …
=> Metamorph update

Data/Row/Internal.hs, examples/Examples.lhs
I really wish I could customize how GHC prints out row-types in general, but with this adjustment, at least they pretty-print in my custom error messages.
Also, I fixed some old text that needed to be updated in Examples.lhs.
=> better error messages and fixed examples text

Data/Row/Switch.hs
I've been updating `open-adt` with the changes in #63 for testing purposes before continuing with that pull request, but I appear to need `AppliesTo` exported so I can use it in constraints when using `switch`/`caseon`. This pull request adds `AppliesTo` to the exports of `Data.Row.Switch`.
=> Export AppliesTo from Data.Row.Switch

Data/Row/Dictionaries.hs, Data/Row/Internal.hs, Data/Row/Variants.hs
ApSingle is like Ap, except a row of type operators are applied to a single type instead of a row of types.
As mentioned in https://github.com/target/row-types/pull/53#issuecomment-651382910, this adds ApplyRow renamed to ApSingle. Compared to ApplyRow, I reordered the arguments of ApSingle so it more closely matches Ap.
Please let me know if you'd like any changes!
=> Add ApSingle

Data/Row.hs, Data/Row/Dictionaries.hs, Data/Row/Internal.hs, Data/Row/Records.hs, Data/Row/Switch.hs, Data/Row/Variants.hs, examples/Examples.lhs
This is pretty expansive, but it comes down to a core idea: that `trial` should put its successful result in the `Right` instead of the `Left` (https://github.com/target/row-types/issues/54).  This has a bit of a rippling effect that made me change the order of arguments to the bifunctor in `metamorph`.  In total, this certainly breaks lots of internals as well as anyone who uses `trial`, `multiTrial`, or `split`.
I also added a few reasonable exports, including a few new record and variant functions that may be convenient.
=> Flip some arguments

src/Data/Row/Dictionaries.hs, src/Data/Row/Records.hs, src/Data/Row/Variants.hs
Added `Vectors.fromLabelsMap`, which allows one to create a value of type `Map f Vec` from labels.
Satisfies https://github.com/target/row-types/issues/66.
I also took the liberty of going through the axioms in `Dictionaries` to make the type variable arguments all come in a consistent and predictable order.
=> Add fromLabelsMap

.github/workflows/ci.yml
Due to some recent changes int GitHub Actions, we need to update to the latest version of [setup-haskell](https://github.com/actions/setup-haskell).
According to their site, setting it to `v1` should make it automatically pull the latest version, so we don't need to manually update in the future.
=> Fix Github CI

row-types.cabal, src/Data/Row/Internal.hs, tests/Main.hs, tests/UnionPerformance.hs
GHC uses exponential(?) amounts of memory on MinJoinR and ConstUnionR when there are nested calls with many overlapping keys. This can be worked around by specializing `Ifte` to the branches we need in the two cases.
=> Work around poor GHC performance on MinJoinR and ConstUnionR

src/Data/Row/Records.hs, src/Data/Row/Variants.hs
Hi, it's been a while ☺
I've been playing with the intersection of [polymorphic variants, open recursion, lenses], for which i need this.
=> Generalize many kinds, and generalize some constraints from `Applicative` to `Functor`.

row-types.cabal, src/Data/Row/Internal.hs, tests/DiffPerformance.hs, tests/Main.hs, tests/MergePerformance.hs
The problem is the same as in #71.
I also have tried to fix `Inject` and `LacksR` but haven't found tests cases with bad performance.
=> Work around poor GHC performance on Diff and Merge
